"""ArmCor: Armenian corpus-based statistical post-correction for OCR text.

Uses word- and character-level frequency data from a reference Armenian
corpus to detect and correct likely OCR errors.  The approach is
language-model-free: it relies on n-gram frequencies and edit distance
to pick the most probable correction for each unknown token.

The module loads a frequency dictionary (JSON mapping word → count) and
uses it to score candidate corrections generated by single-character edits
within the Armenian Unicode range.

Supports variant-aware correction: when configured with separate Western
Armenian and Eastern Armenian frequency files, the module auto-detects the
language variant of the input text (via the branch dialect classifier) and
applies the matching corpus.  A ``variant`` parameter ("western", "eastern",
or "auto") controls this behaviour.

Configuration
~~~~~~~~~~~~~
.. code-block:: yaml

    ocr:
      armcor_correction: auto            # true | false | "auto"
      armcor_freq_path: ""               # path to word-frequency JSON (fallback)
      armcor_freq_path_wa: ""            # Western Armenian frequency JSON
      armcor_freq_path_ea: ""            # Eastern Armenian frequency JSON
      armcor_min_freq: 3                 # minimum corpus frequency to trust
      armcor_max_edit_distance: 1        # max Levenshtein edits per token
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Armenian Unicode range for character replacements.
_ARMENIAN_LOWER = "\u0561\u0562\u0563\u0564\u0565\u0566\u0567\u0568\u0569\u056A\u056B\u056C\u056D\u056E\u056F\u0570\u0571\u0572\u0573\u0574\u0575\u0576\u0577\u0578\u0579\u057A\u057B\u057C\u057D\u057E\u057F\u0580\u0581\u0582\u0583\u0584\u0585\u0586\u0587"
_ARMENIAN_UPPER = "\u0531\u0532\u0533\u0534\u0535\u0536\u0537\u0538\u0539\u053A\u053B\u053C\u053D\u053E\u053F\u0540\u0541\u0542\u0543\u0544\u0545\u0546\u0547\u0548\u0549\u054A\u054B\u054C\u054D\u054E\u054F\u0550\u0551\u0552\u0553\u0554\u0555\u0556"
_ARM_CHARS = list(_ARMENIAN_LOWER + _ARMENIAN_UPPER)

_ARMENIAN_RE = re.compile(r"[\u0530-\u058F]")
_TOKEN_SPLIT_RE = re.compile(r"(\S+)")

# Per-path frequency cache: maps resolved path string → freq dict.
_freq_cache: dict[str, dict[str, int]] = {}

# Legacy single-dict cache (kept for backward-compatible callers).
_freq_dict: dict[str, int] | None = None
_freq_path_loaded: str = ""

DEFAULT_MIN_FREQ = 3
DEFAULT_MAX_EDIT_DISTANCE = 1

# Valid variant names accepted by the public API.
_VALID_VARIANTS = frozenset({"western", "eastern", "auto"})


def _load_freq_file(freq_path: str | Path) -> dict[str, int]:
    """Load a single frequency JSON and cache by resolved path."""
    path_str = str(freq_path)
    if path_str in _freq_cache:
        return _freq_cache[path_str]

    p = Path(freq_path)
    if not p.exists():
        logger.warning("ArmCor frequency file not found: %s", freq_path)
        _freq_cache[path_str] = {}
        return _freq_cache[path_str]

    try:
        with open(p, encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict):
            logger.warning("ArmCor frequency file is not a dict: %s", freq_path)
            _freq_cache[path_str] = {}
        else:
            _freq_cache[path_str] = {k: int(v) for k, v in data.items()}
            logger.info(
                "ArmCor frequencies loaded: %d words from %s",
                len(_freq_cache[path_str]), freq_path,
            )
    except Exception as exc:
        logger.warning("Failed to load ArmCor frequencies: %s", exc)
        _freq_cache[path_str] = {}

    return _freq_cache[path_str]


def load_armcor_frequencies(freq_path: str | Path) -> dict[str, int]:
    """Load word-frequency dictionary from a JSON file.

    Expected format: ``{"word": count, ...}``

    Returns an empty dict if the file doesn't exist or can't be parsed.
    """
    global _freq_dict, _freq_path_loaded

    path_str = str(freq_path)
    if _freq_dict is not None and _freq_path_loaded == path_str:
        return _freq_dict

    _freq_dict = _load_freq_file(freq_path)
    _freq_path_loaded = path_str
    return _freq_dict


def detect_variant(text: str) -> str:
    """Detect whether *text* is Western or Eastern Armenian.

    Returns ``"western"``, ``"eastern"``, or ``"western"`` as the default
    when detection is inconclusive (Western Armenian is the project default).

    Uses the branch dialect classifier when available; falls back to
    ``"western"`` if the classifier is not installed.
    """
    try:
        from hytools.linguistics.dialect.branch_dialect_classifier import (
            classify_text_classification,
        )
    except ImportError:
        logger.debug("Branch dialect classifier not available; defaulting to western")
        return "western"

    result = classify_text_classification(text)
    label = result.get("label", "")

    if "eastern" in label:
        return "eastern"
    # "likely_western", "likely_classical", "inconclusive" → western
    return "western"


def resolve_freq(
    *,
    variant: str = "auto",
    text: str = "",
    freq: dict[str, int] | None = None,
    freq_path: str | Path = "",
    freq_path_wa: str | Path = "",
    freq_path_ea: str | Path = "",
) -> dict[str, int]:
    """Pick the right frequency dict for a correction run.

    Resolution order:

    1. If *freq* is passed directly, use it (ignores variant).
    2. If *variant* is ``"auto"``, detect from *text*.
    3. Load the variant-specific path (``freq_path_wa`` / ``freq_path_ea``)
       if provided, otherwise fall back to the generic ``freq_path``.
    """
    if freq is not None:
        return freq

    if variant == "auto":
        variant = detect_variant(text) if text else "western"

    if variant == "western" and freq_path_wa:
        return _load_freq_file(freq_path_wa)
    if variant == "eastern" and freq_path_ea:
        return _load_freq_file(freq_path_ea)

    # Fallback to generic path.
    if freq_path:
        return load_armcor_frequencies(freq_path)

    return {}


def _is_armenian_token(token: str) -> bool:
    """Return True when *token* contains at least one Armenian character."""
    return bool(_ARMENIAN_RE.search(token))


def _strip_punct(token: str) -> tuple[str, str, str]:
    """Split leading/trailing punctuation from a token core.

    Returns ``(prefix_punct, core, suffix_punct)``.
    """
    start = 0
    end = len(token)
    while start < end and not token[start].isalpha():
        start += 1
    while end > start and not token[end - 1].isalpha():
        end -= 1
    return token[:start], token[start:end], token[end:]


def _generate_edit1_candidates(word: str) -> set[str]:
    """Generate all strings that are 1 edit distance from *word*.

    Edits: deletions, transpositions, replacements, insertions — all
    restricted to Armenian characters.
    """
    splits = [(word[:i], word[i:]) for i in range(len(word) + 1)]
    candidates: set[str] = set()

    # Deletions
    for a, b in splits:
        if b:
            candidates.add(a + b[1:])

    # Transpositions
    for a, b in splits:
        if len(b) > 1:
            candidates.add(a + b[1] + b[0] + b[2:])

    # Replacements (Armenian chars only)
    for a, b in splits:
        if b:
            for c in _ARM_CHARS:
                candidates.add(a + c + b[1:])

    # Insertions (Armenian chars only)
    for a, b in splits:
        for c in _ARM_CHARS:
            candidates.add(a + c + b)

    candidates.discard(word)
    return candidates


def _best_correction(
    word: str,
    freq: dict[str, int],
    min_freq: int = DEFAULT_MIN_FREQ,
    max_edit: int = DEFAULT_MAX_EDIT_DISTANCE,
) -> str | None:
    """Find the highest-frequency corpus word within *max_edit* edits.

    Returns the correction or ``None`` if the word is already known
    or no better candidate exists.
    """
    # Already a known word — don't "correct" it
    if word in freq and freq[word] >= min_freq:
        return None

    # Also check lowercase
    lower = word.lower()
    if lower in freq and freq[lower] >= min_freq:
        return None

    candidates = _generate_edit1_candidates(lower)
    if max_edit >= 2:
        edit2: set[str] = set()
        for c in candidates:
            edit2 |= _generate_edit1_candidates(c)
        candidates |= edit2

    # Filter to known words above frequency threshold
    valid = {c: freq[c] for c in candidates if c in freq and freq[c] >= min_freq}
    if not valid:
        return None

    best = max(valid, key=valid.get)  # type: ignore[arg-type]
    return best


def armcor_correct(
    text: str,
    freq: dict[str, int] | None = None,
    freq_path: str | Path = "",
    min_freq: int = DEFAULT_MIN_FREQ,
    max_edit: int = DEFAULT_MAX_EDIT_DISTANCE,
    *,
    variant: str = "auto",
    freq_path_wa: str | Path = "",
    freq_path_ea: str | Path = "",
) -> str:
    """Apply corpus-frequency-based correction to Armenian tokens in *text*.

    Either supply *freq* directly or provide frequency-file paths.
    Non-Armenian tokens pass through unchanged.

    Parameters
    ----------
    variant : ``"western"`` | ``"eastern"`` | ``"auto"``
        Which corpus to use.  ``"auto"`` runs the branch dialect classifier
        on *text* and picks the matching corpus.
    freq_path_wa / freq_path_ea :
        Variant-specific frequency JSON paths.  When set, the module loads
        the appropriate file based on *variant*.  Falls back to *freq_path*
        (the generic path) if the variant-specific path is empty.
    """
    resolved = resolve_freq(
        variant=variant,
        text=text,
        freq=freq,
        freq_path=freq_path,
        freq_path_wa=freq_path_wa,
        freq_path_ea=freq_path_ea,
    )

    if not resolved:
        return text

    parts = _TOKEN_SPLIT_RE.split(text)  # odd indices are tokens
    corrections = 0
    for i in range(1, len(parts), 2):
        token = parts[i]
        if not _is_armenian_token(token):
            continue

        prefix, core, suffix = _strip_punct(token)
        if not core:
            continue

        fix = _best_correction(core, resolved, min_freq=min_freq, max_edit=max_edit)
        if fix is not None:
            # Preserve original casing pattern if the core was capitalized
            if core[0].isupper() and fix[0].islower():
                fix = fix[0].upper() + fix[1:]
            parts[i] = prefix + fix + suffix
            corrections += 1

    if corrections:
        logger.debug("ArmCor: corrected %d tokens", corrections)
    return "".join(parts)


def reset() -> None:
    """Reset cached frequency data (useful for testing)."""
    global _freq_dict, _freq_path_loaded
    _freq_dict = None
    _freq_path_loaded = ""
    _freq_cache.clear()
